/*Programmer: Austin Parker
Date: May 29, 2020
Assignment: Chapter 3 / PE 3.17/ RockPaperScissors
Description: User plays Rock,Paper, Scissors with computer*/

import java.util.Random;
import java.util.Scanner;

public class RockPaperScissors {
    public static void main(String[] args) {

        /*reviews user input*/
        Scanner in = new Scanner(System.in);

        /* Random method */
        Random random = new Random();

        /*creates variable for next random integer generated by computer*/
        int computer = random.nextInt(3);
        System.out.print("scissor (0), rock (1), paper (2): ");

        /*creates variable for next integer input from user*/
        int userNumber = in.nextInt();

        /* if statement for determining winner*/
        if (computer == 0) {
            if (userNumber == 0)
                System.out.print("The computer is scissor. You are scissor too. It is a draw");
            else if (userNumber == 1)
                System.out.print("The computer is scissor. You are rock. You won");
            else
                System.out.print("The computer is scissor. You are paper. You lost");
        } else if (computer == 1) {
            if (userNumber == 0)
                System.out.print("The computer is rock. You are scissor. You lost");
            else if (userNumber == 1)
                System.out.print("The computer is rock. You are rock too. It is a draw");
            else
                System.out.print("The computer is rock. You are paper. You won");
        } else if (computer == 2) {
            if (userNumber == 0)
                System.out.print("The computer is paper. You are scissor. You won");
            else if (userNumber == 1)
                System.out.print("The computer is paper. You are rock. You lost");
            else
                System.out.print("The computer is paper. You are paper too. It is a draw");
        }
        /*prints results of program to console*/
        System.out.println();
    }

}


